#!/usr/bin/env bash
ELF_FILE=`echo $* | awk -F ' ' '{print $3}'`
HEX_FILE=${ELF_FILE/\.elf/.hex} 
BIN_FILE=`basename ${ELF_FILE/\.elf/.bin}`
avr-objcopy -I ihex $HEX_FILE -O binary $BIN_FILE 
echo -ne "./${BIN_FILE}\nAUTOGEN\n" | ./get_metadata

# But in old BL to re-flash with EEPROM burner
../miniboot/src/resetboot.sh

# Flash with EEPROM burner
/opt/Arduino/arduino-builder -dump-prefs -logger=machine -hardware /opt/Arduino/hardware -hardware /home/m/.arduino15/packages -tools /opt/Arduino/tools-builder -tools /opt/Arduino/hardware/tools/avr -tools /home/m/.arduino15/packages -built-in-libraries /opt/Arduino/libraries -libraries /home/m/Arduino/libraries -fqbn=arduino:avr:nano:cpu=atmega328old -vid-pid=1A86_7523 -ide-version=10809 -build-path /tmp/arduino_build_988847 -warnings=none -build-cache /tmp/arduino_cache_51170 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2 -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2 -prefs=runtime.tools.arduinoOTA.path=/home/m/.arduino15/packages/arduino/tools/arduinoOTA/1.2.1 -prefs=runtime.tools.arduinoOTA-1.2.1.path=/home/m/.arduino15/packages/arduino/tools/arduinoOTA/1.2.1 -prefs=runtime.tools.avrdude.path=/home/m/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14 -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=/home/m/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14 -verbose /home/m/Arduino/LED2/slave_payload_assembler/output/output.ino
/opt/Arduino/arduino-builder -compile -logger=machine -hardware /opt/Arduino/hardware -hardware /home/m/.arduino15/packages -tools /opt/Arduino/tools-builder -tools /opt/Arduino/hardware/tools/avr -tools /home/m/.arduino15/packages -built-in-libraries /opt/Arduino/libraries -libraries /home/m/Arduino/libraries -fqbn=arduino:avr:nano:cpu=atmega328old -vid-pid=1A86_7523 -ide-version=10809 -build-path /tmp/arduino_build_988847 -warnings=none -build-cache /tmp/arduino_cache_51170 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2 -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2 -prefs=runtime.tools.arduinoOTA.path=/home/m/.arduino15/packages/arduino/tools/arduinoOTA/1.2.1 -prefs=runtime.tools.arduinoOTA-1.2.1.path=/home/m/.arduino15/packages/arduino/tools/arduinoOTA/1.2.1 -prefs=runtime.tools.avrdude.path=/home/m/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14 -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=/home/m/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14 -verbose /home/m/Arduino/LED2/slave_payload_assembler/output/output.ino
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/cores/arduino -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/variants/eightanaloginputs /tmp/arduino_build_988847/sketch/output.ino.cpp -o /dev/null
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/cores/arduino -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/variants/eightanaloginputs -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src /tmp/arduino_build_988847/sketch/output.ino.cpp -o /dev/null
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/cores/arduino -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/variants/eightanaloginputs -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src /home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src/Wire.cpp -o /dev/null
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/cores/arduino -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/variants/eightanaloginputs -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src /home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src/utility/twi.c -o /dev/null
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/cores/arduino -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/variants/eightanaloginputs -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src /tmp/arduino_build_988847/sketch/output.ino.cpp -o /tmp/arduino_build_988847/preproc/ctags_target_for_gcc_minus_e.cpp
/opt/Arduino/tools-builder/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /tmp/arduino_build_988847/preproc/ctags_target_for_gcc_minus_e.cpp
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/cores/arduino -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/variants/eightanaloginputs -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src /tmp/arduino_build_988847/sketch/output.ino.cpp -o /tmp/arduino_build_988847/sketch/output.ino.cpp.o
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/cores/arduino -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/variants/eightanaloginputs -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src /home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src/Wire.cpp -o /tmp/arduino_build_988847/libraries/Wire/Wire.cpp.o
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/cores/arduino -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/variants/eightanaloginputs -I/home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src /home/m/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src/utility/twi.c -o /tmp/arduino_build_988847/libraries/Wire/utility/twi.c.o
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-gcc -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -o /tmp/arduino_build_988847/output.ino.elf /tmp/arduino_build_988847/sketch/output.ino.cpp.o /tmp/arduino_build_988847/libraries/Wire/Wire.cpp.o /tmp/arduino_build_988847/libraries/Wire/utility/twi.c.o /tmp/arduino_build_988847/../arduino_cache_51170/core/core_arduino_avr_nano_cpu_atmega328old_bf426840ba0d2065046d8eebc056a334.a -L/tmp/arduino_build_988847 -lm
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 /tmp/arduino_build_988847/output.ino.elf /tmp/arduino_build_988847/output.ino.eep
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-objcopy -O ihex -R .eeprom /tmp/arduino_build_988847/output.ino.elf /tmp/arduino_build_988847/output.ino.hex
/home/m/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-size -A /tmp/arduino_build_988847/output.ino.elf
/home/m/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/bin/avrdude -C/home/m/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/etc/avrdude.conf -v -patmega328p -carduino -P/dev/ttyUSB0 -b57600 -D -Uflash:w:/tmp/arduino_build_988847/output.ino.hex:i 

# Watch serial stream from arduino, it'll say when EEPROM is burnt. 
#screen -h 0 -D -m -L /dev/ttyUSB0 115200 &

